// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-LvwQxoasHVU8DaKXgF14NfAoIdSUja0',
    appId: '1:623361235930:web:7005a682405c6df0b9fee3',
    messagingSenderId: '623361235930',
    projectId: 'carde-5436a',
    authDomain: 'carde-5436a.firebaseapp.com',
    storageBucket: 'carde-5436a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABanROq1qfMCkEjA8Kv21YMXIlOsob4qg',
    appId: '1:623361235930:android:0bcfe782a75dd78ab9fee3',
    messagingSenderId: '623361235930',
    projectId: 'carde-5436a',
    storageBucket: 'carde-5436a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPXfZfdl-iRXPuKKiBUt6vXF6RPtOpnqI',
    appId: '1:623361235930:ios:bf00e2396a8a9f19b9fee3',
    messagingSenderId: '623361235930',
    projectId: 'carde-5436a',
    storageBucket: 'carde-5436a.appspot.com',
    iosBundleId: 'com.example.cardealership',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPXfZfdl-iRXPuKKiBUt6vXF6RPtOpnqI',
    appId: '1:623361235930:ios:bf00e2396a8a9f19b9fee3',
    messagingSenderId: '623361235930',
    projectId: 'carde-5436a',
    storageBucket: 'carde-5436a.appspot.com',
    iosBundleId: 'com.example.cardealership',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-LvwQxoasHVU8DaKXgF14NfAoIdSUja0',
    appId: '1:623361235930:web:07978181885d480ab9fee3',
    messagingSenderId: '623361235930',
    projectId: 'carde-5436a',
    authDomain: 'carde-5436a.firebaseapp.com',
    storageBucket: 'carde-5436a.appspot.com',
  );
}
